---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: operator-ci-pr
  annotations:
    # Pipelines-as-Code annotations for GitHub/GitLab
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main, master]"
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineRef:
    name: operator-ci-cd
  params:
    - name: repo-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: image
      value: "{{registry}}/k8s-operator:pr-{{pull_request_number}}-{{short_sha}}"
    - name: skip-deploy
      value: "true"  # Don't deploy on PR builds
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: docker-credentials
