---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: operator-ci-push
  annotations:
    # Pipelines-as-Code annotations for GitHub/GitLab
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main, master]"
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "10"
spec:
  pipelineRef:
    name: operator-ci-cd
  params:
    - name: repo-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: image
      value: "{{registry}}/k8s-operator:{{short_sha}}"
    - name: namespace
      value: "default"
    - name: skip-deploy
      value: "false"  # Deploy on main branch
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-credentials
      secret:
        secretName: docker-credentials
